from __future__ import annotations

from pathlib import Path

from bian_engine import __version__
from bian_engine.model import ModelSnapshot
from bian_engine.serialization import canonical_json_bytes, sha256_bytes, write_bytes
from bian_engine.validate import validate_snapshot


def _summary(snapshot: ModelSnapshot) -> bytes:
    domains = [item for item in snapshot.artifacts if item.kind == "service-domain"]
    apis = [item for item in snapshot.artifacts if item.kind == "api-specification"]
    operations = [item for item in snapshot.artifacts if item.kind == "service-operation"]
    domain_rows = []
    for domain in sorted(domains, key=lambda item: (item.name.casefold(), item.artifact_id)):
        api_status = (
            "published API represented"
            if domain.attributes["publishedApiSpecification"]
            else "no API represented"
        )
        domain_rows.append(f"| {domain.name} | `{domain.artifact_id}` | {api_status} |")

    source_rows = [
        f"- `{source.source_id}` — {source.classification}; SHA-256 `{source.digest}`"
        for source in snapshot.source_set
    ]
    content = [
        "<!-- Generated by bian-model-engine; do not edit. -->",
        "# Model catalogue summary",
        "",
        f"- Snapshot: `{snapshot.snapshot_id}`",
        f"- Declared release: `{snapshot.bian_release}`",
        f"- Service Domains: {len(domains)}",
        f"- API specifications: {len(apis)}",
        f"- Service operations: {len(operations)}",
        "",
        "## Imported sources",
        "",
        *source_rows,
        "",
        "## Service Domains",
        "",
        "| Domain | Canonical ID | API status |",
        "|---|---|---|",
        *domain_rows,
        "",
        "> API status reports only what the imported source represents. "
        "The engine does not invent missing operations.",
        "",
    ]
    return "\n".join(content).encode("utf-8")


def build_outputs(snapshot: ModelSnapshot, output_dir: Path) -> dict[str, str]:
    validate_snapshot(snapshot)
    model_bytes = canonical_json_bytes(snapshot.to_dict())
    summary_bytes = _summary(snapshot)
    output_digests = {
        "catalog-summary.md": sha256_bytes(summary_bytes),
        "model.json": sha256_bytes(model_bytes),
    }
    manifest = {
        "manifestVersion": "1.0",
        "engineVersion": __version__,
        "snapshotId": snapshot.snapshot_id,
        "inputs": [
            {"sourceId": source.source_id, "sha256": source.digest}
            for source in snapshot.source_set
        ],
        "outputs": [
            {"path": path, "sha256": digest} for path, digest in sorted(output_digests.items())
        ],
    }
    manifest_bytes = canonical_json_bytes(manifest)

    write_bytes(output_dir / "model.json", model_bytes)
    write_bytes(output_dir / "catalog-summary.md", summary_bytes)
    write_bytes(output_dir / "build-manifest.json", manifest_bytes)
    return {**output_digests, "build-manifest.json": sha256_bytes(manifest_bytes)}
